services:
  mongo:
    image: mongo:4.2.2
    network_mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER-admin}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASS-123456}"
      MONGO_INITDB_DATABASE: "${DB_NAME-dmhy_indexer}"
  rabbitmq:
    image: "rabbitmq:4.1"
    network_mode: host
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER-ciuser}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS-cipassword}"
  main:
    build:
      context: .
      target: dev
    image: "indexer"
    network_mode: host
    command: npm run start
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "3"
    environment:
      MODE_LIST: "${MODE_LIST-dmhy}"
      DB_HOST: "${DB_HOST-mongo}"
      DB_PORT: "${DB_PORT-27017}"
      DB_USER: "${DB_USER-admin}"
      DB_PASS: "${DB_PASS-123456}"
      AUTH_SOURCE: "${AUTH_SOURCE-admin}"
      SERVER_HOST: "${SERVER_HOST-0.0.0.0}"
      MIN_INTERVAL: "${MIN_INTERVAL-10000}"
      MIN_CHECK_INTERVAL: "${MIN_CHECK_INTERVAL-900000}"
      MIN_FAILED_TASK_CHECK_INTERVAL: "${MIN_FAILED_TASK_CHECK_INTERVAL-1800000}"
      MAX_PAGE_NO: ${MAX_PAGE_NO-5}
      MAX_SEARCH_COUNT: ${MAX_SEARCH_COUNT-100}
      SENTRY_DSN: ${SENTRY_DSN}
      AMQP_URL: "${AMQP_URL-amqp://ciuser:cipassword@rabbitmq:5672/}"
      AMQP_MANAGEMENT_API_URL: "${AMQP_MANAGEMENT_API_URL-http://ciuser:cipassword@localhost:15672/api}"
      AMQP_SERVER_TYPE: "{AMQP_SERVER_TYPE-RabbitMQ}"
      AMQP_VHOST: "{AMQP_VHOST-/}"
    volumes:
      - ".:/irohalab/indexer"
      - "/irohalab/indexer/node_modules"
      - "/irohalab/indexer/dist"
    depends_on:
      - mongo
      - rabbitmq
