name: release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  release-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Sentry CLI
      run: curl -sL https://sentry.io/get-cli/ | bash
    - name: Create a release
      run: |
        export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
        export SENTRY_ORG=${{ secrets.SENTRY_ORG }}
        export SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}
        export VERSION=indexer@$(git describe --tags)
        sentry-cli releases new $VERSION
        sentry-cli releases set-commits --auto $VERSION

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: irohalab/mira-resource-indexer/indexer
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        buildoptions: "--target prod"
        registry: docker.pkg.github.com
        tag_names: true

    - name: Finalize release
      run: |
        export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
        export SENTRY_ORG=${{ secrets.SENTRY_ORG }}
        export SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}
        export VERSION=indexer@$(git describe --tags)
        sentry-cli releases finalize $VERSION
