name: release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  release-package:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: irohalab/indexer/indexer
        username:  ${{ secrets.USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        buildoptions: "--target prod"
        registry: docker.pkg.github.com
        tag_names: true
